### ISSUE TITLE
catch.hpp:10735 assumes that MINSIGSTKSZ is a constant which isn't true for glibc 2.34

### ISSUE THREAD

**Issue by billpriest** [CD3/libInterpolate#7]
I upgraded to Ubuntu 21.10 and I started getting this error.  A little googling and found the folllowing:
MINSIGSTKSZ is redefined to sysconf(_SC_MINSIGSTKSZ) starting from glibc 2.34
I changed it to just set it to 32768 as a work-around; but this of course isn't a "correct" fix.

**Comment by CD3** [comment]
Thanks for filing the issue. I am still on 20.04, but I'll try to reproduce the error in a docker container and see if updating Catch2 fixes it.

**Comment by billpriest** [comment]
You're welcome. While googling for potential work-around I saw references to Catch2 being a "fix".

Bill

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by billpriest** [comment]
Hi C.D.,
  An alternative to installing creating a VM to test it you can use crosstool-ng which has an option to build a different glibc.  Although this is typically used to build for other processors (ARM's typically), it is "lighter weight" disk space wise than a whole new VM w/ the added benefit of not having to "set up" a VM w/ all your normal tools.

Bill

________________________________

**Comment by CD3** [comment]
@billpriest Thanks for the tip. I have several docker containers setup to test with different versions of Ubuntu, so it was not any trouble. This should be fixed now.

Thanks again.

**Comment by billpriest** [comment]
I'll update and let you know if I still have issues (doubting it).

Bill
________________________________

**Comment by billpriest** [comment]
WFM.

Thanks for the fix.
________________________________
